# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/v1a-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter v1awifi,$(TARGET_DEVICE)),)

endif
